version: '2'
services:

  app:
    build: 
      context: .
      args:
        - constraint:node==dv-vm1
    image: esepublic/lamp-app-server:php7-ppa-ondrej
    environment:
      - constraint:node==/dv-vm1/
